#!/bin/bash

CLUSTER_NAME="${CLUSTERNAME:-"test-cluster"}"
INSTALL_CHEETAH="${INSTALLCHEETAH:-"true"}"
INSTALL_OCTOPUS="${INSTALLOCTOPUS:-"true"}"
OCTOPUS_VERSION="${OCTOPUSVERSION:-"true"}"
CHEETAH_VERSION="${CHEETAHVERSION:-"true"}"

set -e